### ISSUE TITLE
请教，编译报错？

### ISSUE THREAD

**Issue by fengjunren** [lizhangqu/PinyinIME#1]
你好，导入工程后发现有几处报错
1.SkbContainer类  缺少 android.os.SystemProperties
2.多个类中都缺少定义 mPaddingLeft、mPaddingRight、mPaddingTop、mPaddingBottom	
   例如：SoftKeyboardView ComposingView

**Comment by xiehanchao** [comment]
大佬，你后来怎么解决的？

**Comment by fengjunren** [comment]
问题解决了吗？
可参考这个：
https://github.com/junfengren/PinyinIME

**Comment by xiehanchao** [comment]
谢谢，我把mPaddingLeft都替换成getPaddingLeft()就好使了，不知道原作者咋运行的！！！

**Comment by lizhangqu** [comment]
使用https://github.com/anggrayudi/android-hidden-api 替换AndroidSDK下的android.jar，替换前注意备份
