### ISSUE TITLE
无法重新生成dict_pinyin.dat

### ISSUE THREAD

**Issue by minitriangle** [lizhangqu/PinyinIME#4]
PinyinIME/app/src/main/cpp/command/pinyinime_dictbuilder.cpp 这个代码无法运行，
so文件能重新生成，
dict_pinyin.dat 这个词库文件不能重新生成，指导一下，我想添加下词库的
谢谢，邮箱 ：601128574@qq.com

**Comment by HHsmile** [comment]
android.os.SystemProperties  android  studuio 是怎么回去这个系统权限的，求指导，谢谢！
 邮箱：1056742394@qq.com

**Comment by xiangfademao** [comment]
词库问题是由于写入词库文件时的size_t与uint32字节不等的问题导致的。具体可以参考下
https://github.com/xiangfademao/PinYinImeDicBuilder
