### ISSUE TITLE
Android Studio 无法编译成功

### ISSUE THREAD

**Issue by Sunbvert** [lizhangqu/PinyinIME#6]
我克隆下来之后在Android studio编译出现以下问题，请问怎么解决？
`No toolchains found in the NDK toolchains folder for ABI with prefix: mipsel-linux-android`

**Comment by 0312birdzhang** [comment]
你这个是缺少NDK的`mipsel-linux-android`toolchains吧，因为有c/c++代码，需要用NDK编译。

**Comment by Sunbvert** [comment]
用这个链接的方案解决了[https://blog.csdn.net/qq_24118527/article/details/82867864](url)。
